package main;


public class PlainBoard 
{

	public static void displayBetterBoard(int input) 
    {
		if (input == 1)
		{
			System.out.println("|							   /	|									  |										   |");
			System.out.println("|							  /	    |									  |										   |");
			System.out.println("|							 /		|									  |										   |");
			System.out.println("|							/		|									  |										   |");
			System.out.println("|						   /		|									  |										   |");
			System.out.println("|						  /			|									  |										   |");
			System.out.println("|						 /			|									  |										   |");
			System.out.println("|						/			|									  |										   |");
			System.out.println("|					   /			|									  |										   |");
			System.out.println("|					  /				|									  |										   |");
			System.out.println("|					 /				|									  |										   |");
			System.out.println("|					/				|									  |										   |");
			System.out.println("|				   /				|									  |										   |");
			System.out.println("|				  /					|									  |										   |");
			System.out.println("|				 /					|									  |										   |");
			System.out.println("________________/_________________________________________________________________________________________________");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("___________________________________________________________________________________________________________________");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
		}
		if (input == 2)
		{
			System.out.println("|							   		|									 /|										   |");
			System.out.println("|							  	    |									/ |										   |");
			System.out.println("|							 		|								   /  |										   |");
			System.out.println("|									|								  /   |										   |");
			System.out.println("|						   			|								 /    |										   |");
			System.out.println("|						  			|								/	  |										   |");
			System.out.println("|						 			|							   /	  |										   |");
			System.out.println("|									|							  /		  |										   |");
			System.out.println("|					   				|							 /	      |										   |");
			System.out.println("|					  				|							/		  |										   |");
			System.out.println("|					 				|						   /		  |										   |");
			System.out.println("|									|						  /			  |										   |");
			System.out.println("|				   					|						 /			  |										   |");
			System.out.println("|				  					|						/			  |										   |");
			System.out.println("|				 					|					   /			  |										   |");
			System.out.println("__________________________________________________________/______________________________________________________");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("___________________________________________________________________________________________________________________");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
		}
		if (input == 3)
		{
			System.out.println("|							   		|									  |										  /|");
			System.out.println("|							  	    |									  |										 / |");
			System.out.println("|							 		|									  |										/  |");
			System.out.println("|									|									  |									   /   |");
			System.out.println("|						   			|									  |									  /    |");
			System.out.println("|						  			|									  |								     / 	   |");
			System.out.println("|						 			|									  |									/      |");
			System.out.println("|									|									  |								   /	   |");
			System.out.println("|					   				|									  |								  /		   |");
			System.out.println("|					  				|									  |								 /		   |");
			System.out.println("|					 				|									  |								/		   |");
			System.out.println("|									|									  |							   /		   |");
			System.out.println("|				   					|									  |							  /			   |");
			System.out.println("|				  					|									  |							 /			   |");
			System.out.println("|				 					|									  |							/			   |");
			System.out.println("___________________________________________________________________________________________________/_______________");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("___________________________________________________________________________________________________________________");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
		}
		if (input == 4)
		{
			System.out.println("|							    	|									  |										   |");
			System.out.println("|							  	    |									  |										   |");
			System.out.println("|							 		|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|						    		|									  |										   |");
			System.out.println("|						    		|									  |										   |");
			System.out.println("|						 			|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|					    			|									  |										   |");
			System.out.println("|					    			|									  |										   |");
			System.out.println("|					 				|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|				    				|									  |										   |");
			System.out.println("|				    				|									  |										   |");
			System.out.println("|				 					|									  |										   |");
			System.out.println("___________________________________________________________________________________________________________________");
			System.out.println("|								/	|									  |										   |");
			System.out.println("|							   /	|									  |										   |");
			System.out.println("|							  / 	|									  |										   |");
			System.out.println("|							 /		|									  |										   |");
			System.out.println("|							/		|									  |										   |");
			System.out.println("|						   /		|									  |										   |");
			System.out.println("|						  /			|									  |										   |");
			System.out.println("|						 /			|									  |										   |");
			System.out.println("|						/			|									  |										   |");
			System.out.println("|					   /			|									  |										   |");
			System.out.println("|					  /				|									  |										   |");
			System.out.println("|					 /				|									  |										   |");
			System.out.println("|					/				|									  |										   |");
			System.out.println("|				   /				|									  |										   |");
			System.out.println("__________________/________________________________________________________________________________________________");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
		}
		if (input == 5)
		{
			System.out.println("|							    	|									  |										   |");
			System.out.println("|							  	    |									  |										   |");
			System.out.println("|							 		|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|						    		|									  |										   |");
			System.out.println("|						    		|									  |										   |");
			System.out.println("|						 			|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|					    			|									  |										   |");
			System.out.println("|					  				|									  |										   |");
			System.out.println("|					 				|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|				    				|									  |										   |");
			System.out.println("|				  					|									  |										   |");
			System.out.println("|				 					|									  |										   |");
			System.out.println("__________________________________________________________________________________________________________________");
			System.out.println("|									|									/ |										   |");
			System.out.println("|									|								   /  |										   |");
			System.out.println("|									|								  /   |										   |");
			System.out.println("|									|								 /    |										   |");
			System.out.println("|									|								/     |										   |");
			System.out.println("|									|							   /	  |										   |");
			System.out.println("|									|							  /	      |										   |");
			System.out.println("|									|							 /	      |										   |");
			System.out.println("|									|							/	      |										   |");
			System.out.println("|									|						   /  		  |										   |");
			System.out.println("|									|						  / 		  |										   |");
			System.out.println("|									|						 /	    	  |										   |");
			System.out.println("|									|						/	    	  |										   |");
			System.out.println("|									|					   /	 		  |										   |");
			System.out.println("__________________________________________________________/________________________________________________________");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
		}
		if (input == 6)
		{
			System.out.println("|							    	|									  |										   |");
			System.out.println("|							  	    |									  |										   |");
			System.out.println("|							 		|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|						    		|									  |										   |");
			System.out.println("|						   			|									  |										   |");
			System.out.println("|						  			|									  |										   |");
			System.out.println("|						 			|									  |										   |");
			System.out.println("|					    			|									  |										   |");
			System.out.println("|					   				|									  |										   |");
			System.out.println("|					  				|									  |										   |");
			System.out.println("|					 				|									  |										   |");
			System.out.println("|				    				|									  |										   |");
			System.out.println("|				   					|									  |										   |");
			System.out.println("|				  					|									  |										   |");
			System.out.println("___________________________________________________________________________________________________________________");
			System.out.println("|									|									  |										  /|");
			System.out.println("|									|									  |										 / |");
			System.out.println("|									|									  |										/  |");
			System.out.println("|									|									  |									   /   |");
			System.out.println("|									|									  |									  /    |");
			System.out.println("|									|									  |									 /     |");
			System.out.println("|									|									  |									/      |");
			System.out.println("|									|									  |								   /	   |");
			System.out.println("|									|									  |								  / 	   |");
			System.out.println("|									|									  |								 /   	   |");
			System.out.println("|									|									  |								/	       |");
			System.out.println("|									|									  |							   / 		   |");
			System.out.println("|									|									  |							  /	     	   |");
			System.out.println("|									|									  |							 /		       |");
			System.out.println("____________________________________________________________________________________________________/______________");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
		}
		if (input == 7)
		{
			System.out.println("|							    	|									  |										   |");
			System.out.println("|							  	    |									  |										   |");
			System.out.println("|							 		|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|						    		|									  |										   |");
			System.out.println("|						   			|									  |										   |");
			System.out.println("|						  			|									  |										   |");
			System.out.println("|						 			|									  |										   |");
			System.out.println("|					    			|									  |										   |");
			System.out.println("|					   				|									  |										   |");
			System.out.println("|					  				|									  |										   |");
			System.out.println("|					 				|									  |										   |");
			System.out.println("|				    				|									  |										   |");
			System.out.println("|				   					|									  |										   |");
			System.out.println("|				  					|									  |										   |");
			System.out.println("___________________________________________________________________________________________________________________");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |								    	   |");
			System.out.println("|									|									  |								    	   |");
			System.out.println("|									|									  |								     	   |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |							    		   |");
			System.out.println("|									|									  |							  	     	   |");
			System.out.println("|									|									  |							 		       |");
			System.out.println("___________________________________________________________________________________________________________________");
			System.out.println("|								   /|									  |										   |");
			System.out.println("|								  / |									  |										   |");
			System.out.println("|								 /  |									  |										   |");
			System.out.println("|								/   |									  |										   |");
			System.out.println("|							   /    |									  |										   |");
			System.out.println("|							  /     |									  |										   |");
			System.out.println("|							 /  	|									  |										   |");
			System.out.println("|							/   	|									  |										   |");
			System.out.println("|						   /  		|									  |										   |");
			System.out.println("|						  / 		|									  |										   |");
			System.out.println("|						 /  		|									  |										   |");
			System.out.println("|						/   		|									  |										   |");
			System.out.println("|					   / 			|									  |										   |");
		}
		if (input == 8)
		{
			System.out.println("|							    	|									  |										   |");
			System.out.println("|							  	    |									  |										   |");
			System.out.println("|							 		|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|						    		|									  |										   |");
			System.out.println("|						   			|									  |										   |");
			System.out.println("|						  			|									  |										   |");
			System.out.println("|						 			|									  |										   |");
			System.out.println("|					    			|									  |										   |");
			System.out.println("|					   				|									  |										   |");
			System.out.println("|					  				|									  |										   |");
			System.out.println("|					 				|									  |										   |");
			System.out.println("|				    				|									  |										   |");
			System.out.println("|				   					|									  |										   |");
			System.out.println("|				  					|									  |										   |");
			System.out.println("___________________________________________________________________________________________________________________");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |								    	   |");
			System.out.println("|									|									  |								    	   |");
			System.out.println("|									|									  |								     	   |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |							    		   |");
			System.out.println("|									|									  |							  	     	   |");
			System.out.println("|									|									  |							 		       |");
			System.out.println("___________________________________________________________________________________________________________________");
			System.out.println("|									|X									 X|										   |");
			System.out.println("|									|  X 							   X  |										   |");
			System.out.println("|									|  	 X						     X    |										   |");
			System.out.println("|									|	   X					   X      |										   |");
			System.out.println("|									|	     X					 X        |										   |");
			System.out.println("|									|	       X  			   X  	      |										   |");
			System.out.println("|									|	         X			 X		 	  |										   |");
			System.out.println("|									|			   X	   X	    	  |										   |");
			System.out.println("|									|				 X	 X	        	  |										   |");
			System.out.println("|									|				   X		    	  |										   |");
			System.out.println("|									|				X	  X    			  |										   |");
			System.out.println("|									|			 X			X 			  |										   |");
			System.out.println("|									|		  X			      X 	      |										   |");
		}
		if (input == 9)
		{
			System.out.println("|							    	|									  |										   |");
			System.out.println("|							  	    |									  |										   |");
			System.out.println("|							 		|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|						    		|									  |										   |");
			System.out.println("|						   			|									  |										   |");
			System.out.println("|						  			|									  |										   |");
			System.out.println("|						 			|									  |										   |");
			System.out.println("|					    			|									  |										   |");
			System.out.println("|					   				|									  |										   |");
			System.out.println("|					  				|									  |										   |");
			System.out.println("|					 				|									  |										   |");
			System.out.println("|				    				|									  |										   |");
			System.out.println("|				   					|									  |										   |");
			System.out.println("|				  					|									  |										   |");
			System.out.println("___________________________________________________________________________________________________________________");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |										   |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |								    	   |");
			System.out.println("|									|									  |								    	   |");
			System.out.println("|									|									  |								     	   |");
			System.out.println("|									|									  |									       |");
			System.out.println("|									|									  |							    		   |");
			System.out.println("|									|									  |							  	     	   |");
			System.out.println("|									|									  |							 		       |");
			System.out.println("___________________________________________________________________________________________________________________");
			System.out.println("|									|									  |X   									  X|");
			System.out.println("|									|									  |	  X				  				   X   |");
			System.out.println("|									|								      |	     X				    		 X     |");
			System.out.println("|									|								      |			X		        	  X        |");
			System.out.println("|									|								      |			   X		 	   X            |");
			System.out.println("|									|								      |				   X	   X     		   |");
			System.out.println("|									|							    	  |					   X        	       |");
			System.out.println("|									|							    	  |				   X		X              |");
			System.out.println("|									|							    	  |			   X			  X            |");
			System.out.println("|									|							    	  |		    X	    		     X 	       |");
			System.out.println("|									|						    		  |	    X     					    X	   |");
			System.out.println("|									|						    		  |X						          X	   |");
			System.out.println("|									|						    		  |							        	  X|");
		}
		
    }
}
			